from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from enm.package import package_stage, remove_packaged_stage
from enm.github import ReleaseError
from enm.project import (
    _write_cmake_initial_cache,
    build,
    create_project,
    generate_ci,
    load_manifest,
    supports_external_apps,
    test,
)
from enm.state import InstalledSdk


class ProjectTests(unittest.TestCase):
    def test_project_is_pinned_to_release_version(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            manifest = load_manifest(root)
            self.assertEqual(manifest["version"], "0.1.0")
            self.assertEqual(manifest["eui"]["version"], "v9.8.7")
            cmake = (root / "CMakeLists.txt").read_text(encoding="utf-8")
            self.assertIn("find_package(EuiNeo ${ENM_EUI_VERSION} EXACT CONFIG REQUIRED)", cmake)
            self.assertIn("add_executable(${ENM_TARGET} src/app.cpp)", cmake)
            self.assertNotIn("v9.8.7", cmake)
            self.assertNotIn("Sample_App", cmake)
            self.assertIn("EUI_NEO_LEGACY_SOURCE", cmake)
            self.assertIn("core/app/glfw_app_main.cpp", cmake)
            self.assertIn("set(CMAKE_CXX_STANDARD 17)", cmake)
            self.assertIn("add_test(NAME ${ENM_TARGET}.app_config COMMAND ${ENM_TARGET}_tests)", cmake)
            self.assertIn("add_executable(${ENM_TARGET}_tests EXCLUDE_FROM_ALL", cmake)
            self.assertNotIn("tests/app_config_test.cpp src/app.cpp", cmake)
            self.assertTrue((root / "src/app.cpp").is_file())
            self.assertTrue((root / "tests/app_config_test.cpp").is_file())
            self.assertFalse((root / "CMakePresets.json").exists())
            self.assertFalse((root / ".github/workflows/build.yml").exists())

    def test_create_project_uses_schema_two_with_empty_toolchain(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            manifest = load_manifest(root)
            self.assertEqual(manifest["schema"], 2)
            self.assertIn("toolchain", manifest)
            self.assertEqual(manifest["toolchain"], {})

    def test_load_manifest_accepts_schema_one(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            manifest_path = root / "enm-project.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            del manifest["toolchain"]
            manifest["schema"] = 1
            manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
            loaded = load_manifest(root)
            self.assertEqual(loaded["schema"], 1)
            self.assertNotIn("toolchain", loaded)

    def test_cmake_cache_is_derived_from_manifest(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            cache = _write_cmake_initial_cache(root, load_manifest(root)).read_text(encoding="utf-8")
            self.assertIn('set(ENM_TARGET "Sample_App"', cache)
            self.assertIn('set(ENM_PROJECT_VERSION "0.1.0"', cache)
            self.assertIn('set(ENM_EUI_VERSION "9.8.7"', cache)
            self.assertEqual(cache.count(" FORCE)"), 3)

    def test_cmake_cache_injects_compiler(self):
        from unittest import mock
        from enm.toolchain import Compiler

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            manifest = load_manifest(root)
            manifest["toolchain"] = {"compiler": "gcc", "version": ">=12"}
            compiler = Compiler(Path("/usr/bin/g++"), "gcc", (13, 2), "g++ 13.2")
            cache = _write_cmake_initial_cache(root, manifest, compiler).read_text(encoding="utf-8")
        self.assertIn('set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE FILEPATH "Generated by ENM" FORCE)', cache)

    def test_resolve_toolchain_compiler_matches_current(self):
        from unittest import mock
        from enm.toolchain import Compiler, resolve_toolchain_compiler

        manifest = {"toolchain": {"compiler": "gcc", "version": ">=12"}}
        current = Compiler(Path("/usr/bin/g++"), "gcc", (13, 2), "g++ 13.2")
        with mock.patch("enm.toolchain.resolve_compiler", return_value=current):
            compiler = resolve_toolchain_compiler(manifest)
        self.assertEqual(compiler, current)

    def test_resolve_toolchain_compiler_falls_back_to_detected(self):
        from unittest import mock
        from enm.toolchain import Compiler, resolve_toolchain_compiler

        manifest = {"toolchain": {"compiler": "clang", "version": ">=14"}}
        current = Compiler(Path("/usr/bin/g++"), "gcc", (13, 2), "g++")
        clang = Compiler(Path("/usr/bin/clang++"), "clang", (15, 0), "clang++ 15.0")
        with mock.patch("enm.toolchain.resolve_compiler", return_value=current):
            with mock.patch("enm.toolchain.detect_compilers", return_value=[clang]):
                compiler = resolve_toolchain_compiler(manifest)
        self.assertEqual(compiler, clang)

    def test_resolve_toolchain_compiler_returns_none_when_no_match(self):
        from unittest import mock
        from enm.toolchain import Compiler, resolve_toolchain_compiler

        manifest = {"toolchain": {"compiler": "msvc", "version": ">=19.44"}}
        gcc = Compiler(Path("/usr/bin/g++"), "gcc", (13, 2), "g++")
        with mock.patch("enm.toolchain.resolve_compiler", return_value=gcc):
            with mock.patch("enm.toolchain.detect_compilers", return_value=[gcc]):
                compiler = resolve_toolchain_compiler(manifest)
        self.assertIsNone(compiler)

    def _make_sdk(self, directory: str, version: str) -> InstalledSdk:
        root = Path(directory) / version
        config = root / "lib/cmake/EuiNeo/EuiNeoConfig.cmake"
        config.parent.mkdir(parents=True)
        config.write_text("function(eui_neo_configure_app target)\nendfunction()\n", encoding="utf-8")
        return InstalledSdk(version, "windows", "x64", root, "sdk.zip", "abc")

    def test_build_raises_on_sdk_mismatch_without_force(self):
        from unittest import mock

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            sdk = self._make_sdk(directory, "v9.8.6")
            store = mock.MagicMock()
            store.get_installed.return_value = sdk
            with self.assertRaises(Exception) as context:
                build(root, store, force=False)
        self.assertIn("active EUI-NEO SDK is v9.8.6", str(context.exception))
        self.assertIn("enm build --force", str(context.exception))

    def test_build_allows_sdk_mismatch_with_force(self):
        from unittest import mock

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            sdk = self._make_sdk(directory, "v9.8.6")
            store = mock.MagicMock()
            store.get_installed.return_value = sdk
            with mock.patch("enm.project._run", return_value=0):
                result = build(root, store, force=True)
        self.assertEqual(result, 0)

    def test_test_raises_on_sdk_mismatch_without_force(self):
        from unittest import mock

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            sdk = self._make_sdk(directory, "v9.8.6")
            store = mock.MagicMock()
            store.get_installed.return_value = sdk
            with self.assertRaises(Exception) as context:
                test(root, store, force=False)
        self.assertIn("active EUI-NEO SDK is v9.8.6", str(context.exception))
        self.assertIn("enm test --force", str(context.exception))

    def test_build_raises_when_pinned_sdk_missing_without_force(self):
        from unittest import mock

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            store = mock.MagicMock()
            store.get_installed.side_effect = ReleaseError("SDK v9.8.7 for windows-x64 is not installed")
            with self.assertRaises(Exception) as context:
                build(root, store, force=False)
        self.assertIn("SDK v9.8.7 for windows-x64 is not installed", str(context.exception))
        self.assertIn("enm build --force", str(context.exception))

    def test_build_uses_active_sdk_when_pinned_sdk_missing_with_force(self):
        from unittest import mock

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            active_sdk = self._make_sdk(directory, "v9.8.6")
            store = mock.MagicMock()
            store.get_installed.side_effect = ReleaseError("SDK v9.8.7 for windows-x64 is not installed")
            store.active.return_value = active_sdk
            with mock.patch("enm.project._run", return_value=0):
                result = build(root, store, force=True)
        self.assertEqual(result, 0)
        store.active.assert_called_once()

    def test_ci_is_explicit_and_quotes_install_source(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "sample"
            create_project(root, "Sample App", "v9.8.7")
            workflow = generate_ci(
                root,
                "v9.8.7",
                "git+https://github.com/example/enm.git@v0.1.0",
            ).read_text(encoding="utf-8")
            self.assertIn('ENM_INSTALL_SPEC: "git+https://github.com/example/enm.git@v0.1.0"', workflow)
            self.assertIn('pip install "$env:ENM_INSTALL_SPEC"', workflow)
            self.assertIn("enm test", workflow)

    def test_external_app_support_is_detected_from_sdk(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            sdk = InstalledSdk("v1.0.0", "windows", "x64", root, "sdk.zip", "abc")
            self.assertFalse(supports_external_apps(sdk))
            config = root / "lib/cmake/EuiNeo/EuiNeoConfig.cmake"
            config.parent.mkdir(parents=True)
            config.write_text("function(eui_neo_configure_app target)\nendfunction()\n", encoding="utf-8")
            self.assertTrue(supports_external_apps(sdk))

    def test_library_only_sdk_uses_legacy_compatibility(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            sdk = InstalledSdk("v0.5.5", "windows", "x64", root, "sdk.zip", "abc")
            targets = root / "lib/cmake/EuiNeo/EuiNeoTargets.cmake"
            targets.parent.mkdir(parents=True)
            targets.write_text("add_library(eui::neo STATIC IMPORTED)\n", encoding="utf-8")
            self.assertTrue(supports_external_apps(sdk))

    def test_package_writes_digest(self):
        with tempfile.TemporaryDirectory() as directory:
            stage = Path(directory) / "dist/app-v1-windows-x64"
            stage.mkdir(parents=True)
            (stage / "app.exe").write_bytes(b"app")
            archive, digest = package_stage(stage, "zip")
            self.assertTrue(archive.exists())
            self.assertIn(archive.name, digest.read_text(encoding="ascii"))
            remove_packaged_stage(stage, stage.parent)
            self.assertFalse(stage.exists())
            self.assertTrue(archive.exists())
            self.assertTrue(digest.exists())


if __name__ == "__main__":
    unittest.main()
